# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

before_install:
    - pip install -r requirements-dev.txt

install:
    - python setup.py install

script:
    - py.test -v --cov-config .coveragerc --cov crimson crimson/tests/
